databases:
  - name: law_db
    plan: free
    databaseName: law_db
    user: low
services:
  - type: web
    name: prepaid-dispute-resolution-platform
    plan: free
    runtime: python
    # region: frankfurt  
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: law_db
          property: postgres://low:d1kZThoPZqo8P3oWFrfUW8Fz0ebbBpuf@dpg-co6g9isf7o1s73diqefg-a/law_db
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.11
