databases:
  - name: law_db
    plan: free
    databaseName: law_db
    user: low
services:
  - type: web
    name: prepaid-dispute-resolution-platform
    plan: free
    env: python
    # region: frankfurt  
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: law_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.11
