# Generated by Django 4.2.9 on 2024-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provements',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files/'),
        ),
        migrations.AddField(
            model_name='provements',
            name='provement',
            field=models.ImageField(blank=True, null=True, upload_to='static/provements/'),
        ),
    ]
