# Generated by Django 4.2.9 on 2024-03-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_provements_file_provements_provement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provements',
            name='provement',
        ),
    ]
