# Generated by Django 4.2.9 on 2024-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_file_remove_provements_file_alter_userinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/covers/'),
        ),
    ]
