# Generated by Django 4.2.9 on 2024-03-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avator',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/avatar'),
        ),
    ]
