# Generated by Django 4.2.9 on 2024-04-07 09:58

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_chatmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='ChatItem',
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
