# Generated by Django 4.2.9 on 2024-04-18 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_remove_userinfo_email_documents_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provements',
            name='document',
            field=models.ForeignKey(default=166, on_delete=django.db.models.deletion.CASCADE, to='home.documents'),
            preserve_default=False,
        ),
    ]
