# Generated by Django 4.2.9 on 2024-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_documents_user_provements_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
