# Generated by Django 4.2.9 on 2024-04-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_avatar',
        ),
    ]
