# Generated by Django 4.2.9 on 2024-04-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_comments_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='user',
        ),
    ]
