# Generated by Django 4.2.9 on 2024-04-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_documents_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provements',
            name='document',
        ),
    ]
